services:
  sim:
    image: "prisoner-dilemma-sim:latest"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
